# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=18)),
                ('ape_pat', models.CharField(max_length=18)),
                ('ape_mat', models.CharField(max_length=18)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
