# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicurso', '0001_initial'),
        ('appdocente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='docente_curso',
            field=models.ManyToManyField(to='aplicurso.curso'),
        ),
    ]
