# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='alumno_curso',
            field=models.ManyToManyField(blank=True, to='aplicurso.curso'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='alumno_docente',
            field=models.ManyToManyField(blank=True, to='appdocente.docente'),
        ),
    ]
