# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicurso', '0001_initial'),
        ('appdocente', '0002_docente_docente_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionalumno', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('fechanac', models.DateField(auto_now=True)),
                ('alumno_curso', models.ManyToManyField(to='aplicurso.curso')),
                ('alumno_docente', models.ManyToManyField(to='appdocente.docente')),
            ],
        ),
    ]
