# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcioncurso', models.CharField(max_length=255)),
                ('creditos', models.IntegerField()),
                ('ciclo', models.CharField(max_length=8)),
                ('estadocurso', models.BooleanField(default=True)),
                ('fechaagregado', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizado', models.DateTimeField(auto_now=True)),
                ('prerequisito', models.ManyToManyField(related_name='_curso_prerequisito_+', to='aplicurso.curso')),
            ],
        ),
        migrations.CreateModel(
            name='tipocurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripciontipocurso', models.CharField(max_length=15)),
                ('estadotipo', models.BooleanField(default=True)),
                ('fechaagregado', models.DateTimeField(auto_now_add=True)),
                ('fechaactualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='tipocurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicurso.tipocurso'),
        ),
    ]
